coverage:
  status:
    project:
      python:
        target: 85%
        flags: python
      C:
        target: 90%
        flags: C

    patch:
      python:
        target: 90%
        flags: python
      C:
        target: 85%
        flags: C
