environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
    - PYTHON: "C:\\Miniconda37-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "git submodule update --init --recursive --remote"

build: false

test_script:
  - "conda config --add channels conda-forge"
  - "conda install --yes --file=requirements/conda-minimal.txt"
  - "pip install PyVCF"  
  - "pip install newick"  
  - "pip install python_jsonschema_objects"

  # There seems to be an issue here, where we're not using the correct 
  # version of Python.
  - "SET MSP_CONDA_PREFIX=%PYTHON%"
  - "python setup.py build_ext --inplace"
  - "python setup.py install"
  # FIXME debugging
  - "python -vc \"import _msprime\""
  - "nosetests -vs"

after_test:
  - "python setup.py bdist_wheel"
