environment:
  matrix:
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "111"

    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"
      CONDA_NPY: "111"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_NPY: "111"

    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      CONDA_PY: "36"
      CONDA_NPY: "111"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: false

test_script:
  - "conda config --add channels conda-forge"
  - "conda install --yes --file=requirements/appveyor.txt"
  - "pip install svgwrite"  # svgwrite isn't available in conda
  - "pip install PyVCF"  

  # There seems to be an issue here, where we're not using the correct 
  # version of Python.
  - "SET MSP_CONDA_PREFIX=%PYTHON%"
  - "python setup.py build_ext --inplace"
  - "nosetests -vs"

after_test:
  - "python setup.py bdist_wheel"
