# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Msprime manual
author: Tskit Developers
copyright: "2021"
# logo: logo.png

execute:
  execute_notebooks: cache

repository:
  url: https://github.com/tskit-dev/msprime
  branch: main
  path_to_book: docs

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

only_build_toc_files: true

parse:
    myst_extended_syntax: true

sphinx:
    local_extensions:
      set_version: "_ext/"
    extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.todo
    - sphinx.ext.intersphinx
    - sphinx_issues
    - sphinxarg.ext
    config:
      issues_github_path: tskit-dev/msprime
      todo_include_todos: true
      intersphinx_mapping:
        tskit: ["https://tskit.readthedocs.io/en/stable", null]
        tutorials: ["https://tskit.dev/tutorials/", null]
        stdpopsim: ["https://stdpopsim.readthedocs.io/en/stable", null]
